apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jp1rvyuko-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jp1rvyuko-python 
  name: jp1rvyuko-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jp1rvyuko-python 
